/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.DelayTest
{
    public class ByteStamped : Message
    {
        public const string RosMessageName = "delay_test_msgs/ByteStamped";

        public Header header { get; set; }
        public UInt8[] data { get; set; }

        public ByteStamped()
        {
            this.header = new Header();
            this.data = new UInt8[0];
        }

        public ByteStamped(Header header, UInt8[] data)
        {
            this.header = header;
            this.data = data;
        }
    }
}
